### ISSUE TITLE
Handling of earSubdeploymentsIsolated might be backwards.

### ISSUE THREAD

**Issue by pluttrell** [mamohr/jboss-deployment-structure#1]
According to the [Wildfly Docs](https://docs.jboss.org/author/display/WFLY8/Developer+Guide#DeveloperGuide-ClassloadinginWildFly8): "By default [<ear-subdeployments-isolated>] is set to false...."

When using this module as follows (setting it to the default value)

```
jbossDeploymentStructure {
    earSubdeploymentsIsolated = false
}
```

_will generate:_

```
<jboss-deployment-structure xmlns="urn:jboss:deployment-structure:1.2">
  <ear-subdeployments-isolated>
    false
  </ear-subdeployments-isolated>
</jboss-deployment-structure>
```

But when using this module as follows (setting it to the non-default value)

```
jbossDeploymentStructure {
    earSubdeploymentsIsolated = true
}
```

_will generate:_

```
<jboss-deployment-structure xmlns="urn:jboss:deployment-structure:1.2">
</jboss-deployment-structure>
```

I think the logic to determine if the element should be included or not, is just backwards...or assumes the default value is `true`.

In addition to fixing the logic, I think a better approach might be to do this: If `earSubdeploymentsIsolated` is included in the Gradle DSL, then include the value in the `jboss-deployment-structure.xml` to whichever entry the user set it to.

**Comment by mamohr** [comment]
Thanks for the hint. The <ear-subdeployments-isolated> tag should now only be present when you define the property. Version with the fix is 0.8.1.
